PORTS = {
    21:   {"service": "FTP",        "risk": "CRITICAL"},
    22:   {"service": "SSH",        "risk": "ATTENTION"},
    23:   {"service": "Telnet",     "risk": "CRITICAL"},
    25:   {"service": "SMTP",       "risk": "ATTENTION"},
    53:   {"service": "DNS",        "risk": "ATTENTION"},
    80:   {"service": "HTTP",       "risk": "COMMON"},
    110:  {"service": "POP3",       "risk": "ATTENTION"},
    135:  {"service": "RPC",        "risk": "CRITICAL"},
    139:  {"service": "NetBIOS",    "risk": "CRITICAL"},
    143:  {"service": "IMAP",       "risk": "ATTENTION"},
    443:  {"service": "HTTPS",      "risk": "COMMON"},
    445:  {"service": "SMB",        "risk": "CRITICAL"},
    1433: {"service": "MSSQL",      "risk": "CRITICAL"},
    1521: {"service": "Oracle DB",  "risk": "CRITICAL"},
    3306: {"service": "MySQL",      "risk": "CRITICAL"},
    3389: {"service": "RDP",        "risk": "CRITICAL"},
    5432: {"service": "PostgreSQL", "risk": "CRITICAL"},
    5900: {"service": "VNC",        "risk": "CRITICAL"},
    6379: {"service": "Redis",      "risk": "CRITICAL"},
    8080: {"service": "HTTP-Alt",   "risk": "COMMON"},
    8443: {"service": "HTTPS-Alt",  "risk": "COMMON"},
    27017:{"service": "MongoDB",    "risk": "CRITICAL"},
}
